name: basic-github-action
env:
  SHA_COMMIT : "commit sha: ${{ github.sha }}"

on:
  push:
    branches:
      - gh-pages
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print hello message
      run : echo "Hello!"
    - name: Show current directory
      run : pwd
      
  my_deploy:
    runs-on: macos-latest
    needs: [my_testing]
    
    steps:
    - name: Show current directory and SHA commit
      run: |
        pwd
        echo "SHA commit: ${{ env.SHA_COMMIT }}" 
