name: basic-github-action

on:
  push:
    branches:
      - gh-pages
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print hello message
      run : echo "Hello!"
    - name: Show current directory
      run : pwd
      
  my_deploy:
    runs-on: macos-latest
    needs: [my_testing]
    
    steps:
    - name: Show current directory
      run: pwd
